### ISSUE TITLE
how can i use laravel passport instead of jwt

### ISSUE THREAD

**Issue by thamibn** [tuandm/laravue-core#18]
i am able to athenticate using my api and get the toke however i am confuse where i need to change so it can read my json repsonse whixh has the token, how are the routes guarded?

**Comment by tuandm** [comment]
@thamibn We are working on applying Laravel passport here: https://github.com/tuandm/laravue/issues/119

**Comment by FreddyCrugger** [comment]
How long will it take do you think to get the Laravel passport added please?

Thanks

**Comment by tuandm** [comment]
@FreddyCrugger 
Sorry for the late updates. We just back to work from big holidays (Lunar New Year). We will try to add Laravel passport in Feb. Also, Laravel Airlock is potential too.

**Comment by FreddyCrugger** [comment]
Thank you for the reply.

**Comment by FreddyCrugger** [comment]
I have always used the Passport on my laravel projects, it is my understanding that with JWT we cannot find out the role of the person. So how to actually know who is who via JWT? With the passport it is easy.

**Comment by thamibn** [comment]
@FreddyCrugger i have implemented laravel passport on this project however i setup the project to use uuid, instead of simple id's if your intrested to clone it let me know since its a private repo.

**Comment by FreddyCrugger** [comment]
Hi Thamibn, this would be fantastic please. Thank you so much!

**Comment by thamibn** [comment]
@FreddyCrugger https://github.com/thamibn/project1.git

**Comment by FreddyCrugger** [comment]
Thank you so much, I have just downloaded it.
So, this is Laravue with the passport instead of the JWT, is there anything else you have changed in it vs the normal Laravue version please?

**Comment by thamibn** [comment]
@FreddyCrugger yes is Laravue with Passport, if i remember well i think i have only changed the id fields to use uuids for Users,Passport and Spatie/Permissions and added categories only you can test the routes on postman. and continue edit from there.

**Comment by FreddyCrugger** [comment]
Thank you so much! I will install now and start working on it from next week. If you need anything please let me know.

**Comment by thamibn** [comment]
Your welcome, i am stuck on how can i use this sidebar [https://azouaoui-med.github.io/pro-sidebar-template/src/#](url) on the laravue project.

if you good in frontend you may help.
