### ISSUE TITLE
api routes

### ISSUE THREAD

**Issue by BechirAhmed** [tuandm/laravue-core#2]
How or Where i can write my own api routes to communicate with my controllers, cuz it works only if i write them in this file vendor\tuandm\laravue-core\src\routes\laravue.php

**Comment by tuandm** [comment]
@BechirAhmed Sorry for that issue. We are working to release the hot fix which removes default routes on the package. In the meantime you can use that file (direct or fork)to add your code, and wait for the new release to move your custom routes later.

**Comment by BechirAhmed** [comment]
Okay, thanks

**Comment by srdjanmarjanovic** [comment]
Any updates here? I was really eager to start using this, but this issue really bugs me ...

**Comment by ramshid** [comment]
I did following tweak to fix this issue

commented following line from `vendor\tuandm\laravue-core\src\routes\laravue.php`

``Route::group(['namespace' => $namespace, 'middleware' => 'web'], function () {
    Route::get('/{any}', 'LaravueController@index')->where('any', '.*');
});``

and added following to my `routes/web.php`

``Route::group(['middleware' => 'web'], function () {
    Route::get('/', '\Tuandm\Laravue\Http\Controllers\LaravueController@index');
});``

now I can use my own controllers. 

Is there any other way to fix this?
