### ISSUE TITLE
How are the roles and permissions set with the navbar?

### ISSUE THREAD

**Issue by FreddyCrugger** [tuandm/laravue-core#23]
Hi,

I love your script but I am having a problem understanding(based on your doc) where in the navbar the roles are set.
When I go to the index.js of the router file, I see no mention of roles but the menus are either showing or not showing based on the selected role. So somewhere, this is set, where? I cannot work it out.

My second problem is with the permissions of:
Element ui
Permission
Components
Charts
Nested routes
Table
Administrator
Theme
Clipboard
Excel
Zip
Pdf
I18n

I can see a popup menu showing me all  of the above but cannot work out where this popup is taking this information from apart from the database.
Do we need to manually input the permissions in the database?

Thank you.

**Comment by tuandm** [comment]
@FreddyCrugger 
This package is to provide all core UI components, not business logic. You should check [Laravue dashboard](https://github.com/tuandm/laravue) for roles/permissions management. Document can be found [here](https://doc.laravue.dev/guide/development/work-with-permission.html)
