### ISSUE TITLE
No element-icons font showing

### ISSUE THREAD

**Issue by Kuzuto** [tuandm/laravue-core#24]
Hi,
Installed a fresh Laravel project and added the laravue-core as described. 
Tried both the automatic and Manuel.

Both installations is missing the Element-UI Icons.
I can't see where the problem is, as it looks like the icons are included in the build.

The full Laravue project, works fine with the Element Icons, but not when I add the laravue-core to a Laravel project.

**Comment by Kuzuto** [comment]
Ok.. found out if I remove :
.options({
      processCssUrls: false
from webpack, then it works..
don't know what other things it might break

**Comment by tuandm** [comment]
@Kuzuto Thanks for pointing out the issue. Yes, your fix is correct and it's added to version 0.4.1.
Laravue core needs to copy Element-UI font by webpack.
