### ISSUE TITLE
LARAVEL 6

### ISSUE THREAD

**Issue by fendipratama** [tuandm/laravue-core#27]
is this compatible with laravel 6?

**Comment by fendipratama** [comment]
../node_modules/webpack-cli/bin/cli.js:93
throw err;

**Comment by fendipratama** [comment]
i got this error message after run 'npm run dev'

**Comment by tuandm** [comment]
@fendipratama Latest version of this package works well with Laravel 6.x/7.x. Please update new release (0.4.0).
