### ISSUE TITLE
Login: Request failed with status code 500

### ISSUE THREAD

**Issue by JeffreyHosler** [tuandm/laravue-core#4]
The POST login works and returns a success message. But even with the success login in the console, i get the 500 error message and then this

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'api_token' in 'where clause' (SQL: select * from `users` where `api_token` = {token} limit 1)

**Comment by tuandm** [comment]
@JeffreyHosler Thanks for reaching this project. Laravue-core uses jwt for guards api driver. Can you please check your config/auth.php and make sure guards.api.driver is `jwt`?

Ref: https://github.com/tuandm/laravue-core#2-config-api-guard

**Comment by JeffreyHosler** [comment]
ahhh yep I had a typo there. Thanks!
