### ISSUE TITLE
No element-icons font showing

### ISSUE THREAD

**Issue by ealopezg** [tuandm/laravue-core#5]
Hi, I installed it on a project that i'm doing but the icons of the menubar dropdown isn't showing. 
I checked the styles index file but is the same as the repository, also checked the blades and webpack.mix.js to check that the fonts will load. But the icons does not show, only shows the svg icons. What I can do?
![Captura de Pantalla 2019-07-20 a la(s) 17 25 46](https://user-images.githubusercontent.com/20019530/61584312-778d7b80-ab13-11e9-87bc-42426238ac3c.png)

**Comment by ealopezg** [comment]
I fixed the problem I had with the icons, I had to change the value processCssUrls in the file webpack.mix.js to true. I will close this issue. Thanks anyway for making this project.

**Comment by tuandm** [comment]
@ealopezg Thanks friend. Happy to hear that you resolved the problem. I plan to take a look at this issue, sorry for this late action...
